; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = atmelavr
board = uno
framework = arduino
monitor_speed=115200

[env:serial-test]
build_flags =
    ; -D TEST_RECEIVER
    ; -D TEST_TRANSMITTER

[env:servo-shield]
build_flags =
    ; -D SERVO_TEST
    ; -D SIMPLE_SERVO
    -D FIND_SERVO_PULSE
lib_deps = 
    https://github.com/adafruit/Adafruit-PWM-Servo-Driver-Library.git
